signatures = ["d7168c60f491ee3bb300c559e8c6d4a050df4791edf1b3c1786731a6fa999d1a"]
source = "GrapheneOS"
hasFsVeritySignatures = true

description = """
Info is a minimal app through which you can get information about the latest releases of GrapheneOS, links to our community spaces, and details on how to make donations.
"""
